import { mkdtemp, mkdir, readFile, realpath, rename, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { createNitro } from 'nitro/builder'
import { afterAll, beforeAll, describe, expect, it, vi } from 'vitest'
import mcp from '../src/module/index.ts'
import { resolveOAuthOptions } from '../src/module/options.ts'
import { clerk } from '../src/runtime/oauth/clerk.ts'
import { fixtureDir, modules } from './helpers/discovery-fixture.ts'
import type { Nitro } from 'nitro/types'

/**
 * A throwaway app directory, at its real path: on Windows `mkdtemp` can answer
 * with an 8.3 short name, which is not the name the filesystem reports back in
 * watch events.
 */
async function tempApp(prefix: string): Promise<string> {
  return realpath(await mkdtemp(join(tmpdir(), prefix)))
}

/** Absolute paths are machine-specific; the shape of the module is not. */
function readable(code: string): string {
  return code.replaceAll(fixtureDir, '<fixture>')
}

/** Reads back what the module logged, without it reaching the test output. */
function logs(nitro: Nitro, level: 'info' | 'warn'): () => string[] {
  const spy = vi.spyOn(nitro.logger, level).mockImplementation(() => {})

  return () => spy.mock.calls.map(([message]) => String(message))
}

async function render(nitro: Nitro, id: string): Promise<string> {
  const template = nitro.options.virtual[id]

  return readable(typeof template === 'function' ? await template() : (template ?? ''))
}

describe('the mcp() module', () => {
  let nitro: Nitro

  beforeAll(async () => {
    // Installs both instances against the fixture tree, without building it.
    nitro = await createNitro({ rootDir: fixtureDir, dev: false, preset: 'standard', modules })
  })

  afterAll(async () => {
    await nitro.close()
  })

  it('mounts each instance on its own route', () => {
    expect(nitro.options.handlers).toMatchObject([
      { route: '/mcp', handler: '#mcp/mcp/handler', lazy: true, middleware: false },
      { route: '/admin/mcp', handler: '#mcp/admin-mcp/handler', lazy: true, middleware: false },
    ])
  })

  it('generates a registry of everything it discovered', async () => {
    await expect(render(nitro, '#mcp/mcp/registry')).resolves.toMatchInlineSnapshot(`
      "// Generated by nitro-mcp-toolkit. Edit the files it lists instead.

      import _0 from "<fixture>/server/mcp/tools/greet-visitor.ts"
      import _1 from "<fixture>/server/mcp/tools/named.ts"
      import _2 from "<fixture>/server/mcp/tools/nested/deep.ts"
      import _3 from "<fixture>/server/mcp/resources/readme.ts"
      import _4 from "<fixture>/server/mcp/prompts/review.ts"

      const fromFile = (definition, { name, title, ...source }) => ({
        ...definition,
        name: definition.name ?? name,
        title: definition.title ?? title,
        source,
      })

      export const tools = [
        fromFile(_0, {"name":"greet-visitor","title":"Greet Visitor","file":"tools/greet-visitor.ts"}),
        fromFile(_1, {"name":"named","title":"Named","file":"tools/named.ts"}),
        fromFile(_2, {"name":"deep","title":"Deep","file":"tools/nested/deep.ts","group":"nested"}),
      ]

      export const resources = [
        fromFile(_3, {"name":"readme","title":"Readme","file":"resources/readme.ts"}),
      ]

      export const prompts = [
        fromFile(_4, {"name":"review","title":"Review","file":"prompts/review.ts"}),
      ]
      "
    `)
  })

  it('exposes every instance from nitro-mcp-toolkit/servers', async () => {
    await expect(render(nitro, 'nitro-mcp-toolkit/servers')).resolves.toMatchInlineSnapshot(`
      "// Generated by nitro-mcp-toolkit. Edit the files it lists instead.
      export { default as mcp } from "#mcp/mcp/handler"
      export { default as adminMcp } from "#mcp/admin-mcp/handler"
      "
    `)
  })

  // On its own app: the generated types live under the root's `node_modules`,
  // and the e2e run builds the shared fixture out of the same directory.
  it('writes extra export names into Nitro generated types', async () => {
    const root = await tempApp('nitro-mcp-types-')
    const typed = await createNitro({
      rootDir: root,
      dev: false,
      preset: 'standard',
      modules: [mcp(), mcp({ route: '/admin/mcp', dir: 'server/mcp-admin' })],
    })

    const dir = join(root, 'node_modules/.nitro/types')
    await mkdir(dir, { recursive: true })
    await writeFile(join(dir, 'nitro.d.ts'), '// generated by nitro\n')

    await typed.hooks.callHook('types:extend', { routes: {} })

    await vi.waitFor(async () => {
      expect(await readFile(join(dir, 'mcp-servers.d.ts'), 'utf8')).toContain(
        'export const adminMcp: McpHandler',
      )
      expect(await readFile(join(dir, 'nitro.d.ts'), 'utf8')).toContain(
        '/// <reference path="./mcp-servers.d.ts" />',
      )
    })

    await typed.close()
    await rm(root, { recursive: true, force: true })
  })

  it('serves each route from its own registry', async () => {
    await expect(render(nitro, '#mcp/admin-mcp/handler')).resolves.toMatchInlineSnapshot(`
      "// Generated by nitro-mcp-toolkit. Edit the files it lists instead.
      import { createMcpHandler } from 'nitro-mcp-toolkit'
      import plugins from "<fixture>/server/mcp-admin/plugins.ts"
      import { prompts, resources, tools } from "#mcp/admin-mcp/registry"

      export default createMcpHandler({
        name: "admin-fixture",
        version: "1.0.0",
        tools,
        resources,
        prompts,
      }, { extensionPlugins: plugins })
      "
    `)
  })

  it('passes what the server advertises through to the handler', async () => {
    const iconic = await createNitro({
      rootDir: fixtureDir,
      dev: false,
      preset: 'standard',
      modules: [
        mcp({
          route: '/iconic',
          icons: [{ src: 'https://example.com/icon.png', mimeType: 'image/png' }],
          websiteUrl: 'https://example.com',
          origin: { allow: ['https://app.example.com'] },
        }),
      ],
    })

    const code = await render(iconic, '#mcp/iconic/handler')

    expect(code).toContain('icons: [{"src":"https://example.com/icon.png","mimeType":"image/png"}]')
    expect(code).toContain('websiteUrl: "https://example.com"')
    expect(code).toContain('origin: {"allow":["https://app.example.com"]}')

    await iconic.close()
  })

  it('passes a static auth config through, tokens and all', async () => {
    const guarded = await createNitro({
      rootDir: fixtureDir,
      dev: false,
      preset: 'standard',
      modules: [mcp({ route: '/guarded', auth: { tokens: ['secret'] } })],
    })

    const code = await render(guarded, '#mcp/guarded/handler')
    expect(code).toContain('auth: {"tokens":["secret"]}')

    await guarded.close()
  })

  it('refuses oauth together with a static token list', () => {
    expect(() =>
      mcp({
        auth: { tokens: ['x'] },
        oauth: {
          resource: 'http://localhost:3030/mcp',
          authorizationServers: ['http://localhost:3030/api/auth'],
          jwt: { jwks: 'http://localhost:3030/api/auth/jwks' },
        },
      }),
    ).toThrow(/cannot both be set/)
  })

  it('refuses oauth without a JWKS URL', () => {
    expect(() =>
      resolveOAuthOptions({
        resource: 'http://localhost:3030/mcp',
        authorizationServers: ['http://localhost:3030/api/auth'],
        jwt: { jwks: '' },
      }),
    ).toThrow(/needs `jwt`/)
  })

  it('generates an oauth instance and mounts RFC 9728 metadata', async () => {
    const guarded = await createNitro({
      rootDir: fixtureDir,
      dev: false,
      preset: 'standard',
      modules: [
        mcp({
          route: '/oauth/mcp',
          dir: 'server/mcp-admin',
          name: 'oauth-fixture',
          oauth: {
            resource: 'http://localhost:3030/oauth/mcp',
            authorizationServers: ['http://localhost:3030/api/auth'],
            jwt: {
              jwks: 'http://localhost:3030/api/auth/jwks',
              issuer: ['http://localhost:3030', 'http://localhost:3030/api/auth'],
            },
            scopesSupported: ['mcp:read'],
          },
        }),
      ],
    })

    expect(guarded.options.handlers).toMatchObject([
      { route: '/oauth/mcp', handler: '#mcp/oauth-mcp/handler' },
      {
        route: '/.well-known/oauth-protected-resource/oauth/mcp',
        handler: '#mcp/oauth-mcp/oauth-metadata',
      },
    ])

    await expect(render(guarded, '#mcp/oauth-mcp/oauth')).resolves.toMatchInlineSnapshot(`
      "// Generated by nitro-mcp-toolkit. Edit the files it lists instead.
      import { createMcpOAuth } from 'nitro-mcp-toolkit'

      export const oauth = createMcpOAuth({
        resource: "http://localhost:3030/oauth/mcp",
        authorizationServers: ["http://localhost:3030/api/auth"],
        scopesSupported: ["mcp:read"],
        jwt: {"jwks":"http://localhost:3030/api/auth/jwks","issuer":["http://localhost:3030","http://localhost:3030/api/auth"]},
      })
      "
    `)

    await expect(render(guarded, '#mcp/oauth-mcp/handler')).resolves.toMatchInlineSnapshot(`
      "// Generated by nitro-mcp-toolkit. Edit the files it lists instead.
      import { createMcpHandler } from 'nitro-mcp-toolkit'
      import { oauth } from "#mcp/oauth-mcp/oauth"
      import plugins from "<fixture>/server/mcp-admin/plugins.ts"
      import { prompts, resources, tools } from "#mcp/oauth-mcp/registry"

      export default createMcpHandler({
        name: "oauth-fixture",
        auth: oauth.auth,
        tools,
        resources,
        prompts,
      }, { extensionPlugins: plugins })
      "
    `)

    await guarded.close()
  })

  it('accepts a connector result and mounts RFC 8414 for old clients', async () => {
    const key = `pk_test_${Buffer.from('acme.clerk.accounts.dev$', 'utf8').toString('base64')}`
    const guarded = await createNitro({
      rootDir: fixtureDir,
      dev: false,
      preset: 'standard',
      modules: [
        mcp({
          route: '/mcp',
          dir: 'server/mcp-admin',
          oauth: clerk({
            publishableKey: key,
            resource: 'http://localhost:3030/mcp',
          }),
        }),
      ],
    })

    expect(guarded.options.handlers).toMatchObject([
      { route: '/mcp', handler: '#mcp/mcp/handler' },
      {
        route: '/.well-known/oauth-protected-resource/mcp',
        handler: '#mcp/mcp/oauth-metadata',
      },
      {
        route: '/.well-known/oauth-authorization-server',
        handler: '#mcp/mcp/oauth-authorization-server',
      },
    ])

    const generated = await render(guarded, '#mcp/mcp/oauth')
    expect(generated).toContain('"https://acme.clerk.accounts.dev"')
    expect(generated).toContain('https://acme.clerk.accounts.dev/.well-known/jwks.json')
    expect(generated).toContain('resource: "http://localhost:3030/mcp"')
    expect(generated).toContain('authorizationServer')

    await guarded.close()
  })

  it('refuses two servers on one route', () => {
    expect(() => mcp().setup(nitro)).toThrow(/Two MCP servers are mounted on \/mcp/)
  })

  it('refuses two routes that export under the same name', async () => {
    await expect(
      createNitro({
        rootDir: fixtureDir,
        dev: false,
        preset: 'standard',
        modules: [mcp({ route: '/2fa/mcp' }), mcp({ route: '/_2fa/mcp' })],
      }),
    ).rejects.toThrow(/both export as `_2faMcp`/)
  })

  it('mounts a route written without its leading slash', async () => {
    const relaxed = await createNitro({
      rootDir: fixtureDir,
      dev: false,
      preset: 'standard',
      modules: [mcp({ route: 'side/mcp/' })],
    })

    expect(relaxed.options.handlers).toMatchObject([{ route: '/side/mcp' }])

    await relaxed.close()
  })

  it('rejects a route that names nothing', () => {
    expect(() => mcp({ route: ' ' })).toThrow(/`route` cannot be empty/)
  })
})

describe('an empty definitions directory', () => {
  it('still generates the three arrays', async () => {
    const nitro = await createNitro({
      rootDir: fixtureDir,
      dev: false,
      preset: 'standard',
      modules: [mcp({ route: '/empty', dir: 'server/nothing-here' })],
    })

    await expect(render(nitro, '#mcp/empty/registry')).resolves.toMatchInlineSnapshot(`
      "// Generated by nitro-mcp-toolkit. Edit the files it lists instead.

      export const tools = []

      export const resources = []

      export const prompts = []
      "
    `)

    await nitro.close()
  })
})

// A definition nobody serves is otherwise silent: the route is still mounted,
// and the files it never reached look exactly like the ones it did.
describe('the report of what each endpoint serves', () => {
  it('lists every instance, and stays quiet until the set changes', async () => {
    const reporting = await createNitro({
      rootDir: fixtureDir,
      dev: false,
      preset: 'standard',
      modules,
    })
    const info = logs(reporting, 'info')

    await reporting.hooks.callHook('compiled', reporting)

    expect(info()).toMatchInlineSnapshot(`
      [
        "[mcp] /mcp serves 3 tools, 1 resource, 1 prompt from server/mcp",
        "[mcp] /admin/mcp serves 1 tool from server/mcp-admin, with plugins.ts",
      ]
    `)

    await reporting.hooks.callHook('compiled', reporting)

    expect(info()).toHaveLength(2)

    await reporting.close()
  })

  it('warns when a route is mounted over nothing', async () => {
    const empty = await createNitro({
      rootDir: fixtureDir,
      dev: false,
      preset: 'standard',
      modules: [mcp({ route: '/empty', dir: 'server/nothing-here' })],
    })
    const warnings = logs(empty, 'warn')

    await empty.hooks.callHook('compiled', empty)

    expect(warnings()).toEqual([
      '[mcp] /empty has no definitions: nothing under server/nothing-here/{tools,resources,prompts}. ' +
        'The route is still mounted, and serves a server with nothing on it.',
    ])

    await empty.close()
  })

  it('warns about a directory named nearly like a scanned one', async () => {
    const root = await tempApp('nitro-mcp-typo-')
    await mkdir(join(root, 'server/mcp/tool'), { recursive: true })
    await mkdir(join(root, 'server/mcp/lib'), { recursive: true })

    const typo = await createNitro({
      rootDir: root,
      dev: false,
      preset: 'standard',
      modules: [mcp()],
    })
    const warnings = logs(typo, 'warn')

    await typo.hooks.callHook('compiled', typo)

    expect(warnings()).toContain(
      '[mcp] server/mcp/tool is not scanned, so nothing in it is served. ' +
        'Rename it to tools if that is what you meant.',
    )
    expect(warnings().join('\n')).not.toContain('server/mcp/lib')

    await typo.close()
    await rm(root, { recursive: true, force: true })
  })
})

// A file already in the registry reaches the bundler through its import; a file
// nobody imports yet needs the registry generated again first.
describe('watching for definitions in development', () => {
  let root: string
  let nitro: Nitro
  let reloads: number

  beforeAll(async () => {
    root = await tempApp('nitro-mcp-watch-')
    await mkdir(join(root, 'server/mcp/tools'), { recursive: true })

    nitro = await createNitro({ rootDir: root, dev: true, preset: 'nitro-dev', modules: [mcp()] })
    reloads = 0
    nitro.hooks.hook('rollup:reload', () => {
      reloads += 1
    })
  })

  afterAll(async () => {
    await nitro.close()
    await rm(root, { recursive: true, force: true })
  })

  it('rebuilds when a definition file appears, and again when it goes', async () => {
    const file = join(root, 'server/mcp/tools/late.ts')

    // The registry already holds what is there: booting is not a change.
    await new Promise((resolve) => setTimeout(resolve, 300))

    expect(reloads).toBe(0)

    await writeFile(file, 'export default {}\n')
    await vi.waitFor(() => expect(reloads).toBeGreaterThan(0), { timeout: 10_000 })

    const afterAdd = reloads

    await rm(file)
    await vi.waitFor(() => expect(reloads).toBeGreaterThan(afterAdd), { timeout: 10_000 })
  })

  // A moved directory reports only itself: no event ever names the files in it.
  it('rebuilds when a directory arrives with definitions already inside', async () => {
    const staged = await tempApp('nitro-mcp-staged-')
    await writeFile(join(staged, 'bulk.ts'), 'export default {}\n')

    const before = reloads

    await rename(staged, join(root, 'server/mcp/tools/bulk'))
    await vi.waitFor(() => expect(reloads).toBeGreaterThan(before), { timeout: 10_000 })
  })

  it('sees a definitions directory that did not exist yet', async () => {
    const late = await tempApp('nitro-mcp-late-')
    const lateNitro = await createNitro({
      rootDir: late,
      dev: true,
      preset: 'nitro-dev',
      modules: [mcp()],
    })
    let lateReloads = 0
    lateNitro.hooks.hook('rollup:reload', () => {
      lateReloads += 1
    })

    await mkdir(join(late, 'server/mcp/tools'), { recursive: true })
    await writeFile(join(late, 'server/mcp/tools/first.ts'), 'export default {}\n')
    await vi.waitFor(() => expect(lateReloads).toBeGreaterThan(0), { timeout: 10_000 })

    await lateNitro.close()
    await rm(late, { recursive: true, force: true })
  })

  // Same reason as a definition file: nothing imports it until the handler is
  // generated again, so only a rebuild can install it.
  it('rebuilds when the plugins file appears, and again when it goes', async () => {
    const file = join(root, 'server/mcp/plugins.ts')
    const before = reloads

    await writeFile(file, 'export default []\n')
    await vi.waitFor(() => expect(reloads).toBeGreaterThan(before), { timeout: 10_000 })

    const afterAdd = reloads

    await rm(file)
    await vi.waitFor(() => expect(reloads).toBeGreaterThan(afterAdd), { timeout: 10_000 })
  })

  it('ignores files that cannot hold a definition', async () => {
    const before = reloads

    await writeFile(join(root, 'server/mcp/notes.md'), 'not a definition\n')
    await writeFile(join(root, 'server/mcp/tools/notes.md'), 'not a definition\n')

    await new Promise((resolve) => setTimeout(resolve, 300))

    expect(reloads).toBe(before)
  })
})
