import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { createNitro } from 'nitro/builder'
import { basename } from 'pathe'
import { describe, expect, it } from 'vitest'
import { discoverPlugins, isPluginsFile } from '../src/module/discover.ts'
import mcp from '../src/module/index.ts'
import { renderHandler } from '../src/module/template.ts'
import { defineMcpPlugins } from '../src/runtime/plugins.ts'

async function appWith(files: Record<string, string>): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), 'nitro-mcp-plugins-'))

  await mkdir(join(root, 'server/mcp/tools'), { recursive: true })

  for (const [file, contents] of Object.entries(files)) {
    await writeFile(join(root, file), contents)
  }

  return root
}

const A_PLUGIN = `export default [{ id: 'fixture/one' }]\n`

describe('defineMcpPlugins', () => {
  // The generated handler passes this very array to `extensionPlugins`, and a
  // plugin instance belongs to one handler, so the helper must not copy it.
  it('hands back the array it was given', () => {
    const plugins = [{ id: 'fixture/one' }]

    expect(defineMcpPlugins(plugins)).toBe(plugins)
  })
})

describe('discovering the plugins file', () => {
  it('finds it under any extension the convention allows', async () => {
    for (const extension of ['ts', 'js', 'mts', 'mjs']) {
      const root = await appWith({ [`server/mcp/plugins.${extension}`]: A_PLUGIN })

      const found = await discoverPlugins(join(root, 'server/mcp'))

      expect(found.map((path) => basename(path))).toEqual([`plugins.${extension}`])

      await rm(root, { recursive: true, force: true })
    }
  })

  it('finds nothing when the app declared none', async () => {
    const root = await appWith({})

    await expect(discoverPlugins(join(root, 'server/mcp'))).resolves.toEqual([])

    await rm(root, { recursive: true, force: true })
  })

  // A definition directory holds definitions; the plugins file sits beside them.
  it('ignores a plugins file inside one of the three directories', async () => {
    const root = await appWith({ 'server/mcp/tools/plugins.ts': A_PLUGIN })

    await expect(discoverPlugins(join(root, 'server/mcp'))).resolves.toEqual([])

    await rm(root, { recursive: true, force: true })
  })

  it('reports every match, so the caller can refuse an ambiguous pair', async () => {
    const root = await appWith({
      'server/mcp/plugins.ts': A_PLUGIN,
      'server/mcp/plugins.mjs': A_PLUGIN,
    })

    const found = await discoverPlugins(join(root, 'server/mcp'))

    expect(found.map((path) => basename(path))).toEqual(['plugins.mjs', 'plugins.ts'])

    await rm(root, { recursive: true, force: true })
  })

  it('recognizes the file only at the root of the scanned directory', () => {
    expect(isPluginsFile('/app/server/mcp', '/app/server/mcp/plugins.ts')).toBe(true)
    expect(isPluginsFile('/app/server/mcp', '/app/server/mcp/plugins.mjs')).toBe(true)
    expect(isPluginsFile('/app/server/mcp', '/app/server/mcp/plugins.json')).toBe(false)
    expect(isPluginsFile('/app/server/mcp', '/app/server/mcp/tools/plugins.ts')).toBe(false)
    expect(isPluginsFile('/app/server/mcp', '/app/server/mcp/setup.ts')).toBe(false)
  })
})

describe('the generated handler', () => {
  it('installs the plugins file as extensionPlugins', () => {
    const code = renderHandler(
      '#mcp/mcp/registry',
      { name: 'app' },
      {
        pluginsPath: '/app/server/mcp/plugins.ts',
      },
    )

    expect(code).toMatchInlineSnapshot(`
      "// Generated by nitro-mcp-toolkit. Edit the files it lists instead.
      import { createMcpHandler } from 'nitro-mcp-toolkit'
      import plugins from "/app/server/mcp/plugins.ts"
      import { prompts, resources, tools } from "#mcp/mcp/registry"

      export default createMcpHandler({
        name: "app",
        tools,
        resources,
        prompts,
      }, { extensionPlugins: plugins })
      "
    `)
  })

  it('takes no second argument when the app declared no plugins', () => {
    const code = renderHandler('#mcp/mcp/registry', { name: 'app' })

    expect(code).not.toContain('extensionPlugins')
    expect(code).toContain('})\n')
  })

  it('installs them alongside oauth', () => {
    const code = renderHandler(
      '#mcp/mcp/registry',
      {},
      {
        oauthId: '#mcp/mcp/oauth',
        pluginsPath: '/app/server/mcp/plugins.ts',
      },
    )

    expect(code).toContain(`import { oauth } from "#mcp/mcp/oauth"`)
    expect(code).toContain('auth: oauth.auth,')
    expect(code).toContain('}, { extensionPlugins: plugins })')
  })
})

describe('the mcp() module with a plugins file', () => {
  it('picks it up from the scanned directory', async () => {
    const root = await appWith({ 'server/mcp/plugins.ts': A_PLUGIN })
    const nitro = await createNitro({
      rootDir: root,
      dev: false,
      preset: 'standard',
      modules: [mcp()],
    })

    const template = nitro.options.virtual['#mcp/mcp/handler']
    const code = typeof template === 'function' ? await template() : ''

    expect(code).toContain('plugins.ts"')
    expect(code).toContain('}, { extensionPlugins: plugins })')

    await nitro.close()
    await rm(root, { recursive: true, force: true })
  })

  // Generated lazily, so a file written after `setup` is seen on the rebuild
  // the watcher asks for rather than needing a restart.
  it('sees a plugins file written after setup ran', async () => {
    const root = await appWith({})
    const nitro = await createNitro({
      rootDir: root,
      dev: false,
      preset: 'standard',
      modules: [mcp()],
    })

    const template = nitro.options.virtual['#mcp/mcp/handler']
    const render = async (): Promise<string> =>
      typeof template === 'function' ? await template() : ''

    expect(await render()).not.toContain('extensionPlugins')

    await writeFile(join(root, 'server/mcp/plugins.ts'), A_PLUGIN)

    expect(await render()).toContain('}, { extensionPlugins: plugins })')

    await nitro.close()
    await rm(root, { recursive: true, force: true })
  })

  it('refuses two plugins files on one route', async () => {
    const root = await appWith({
      'server/mcp/plugins.ts': A_PLUGIN,
      'server/mcp/plugins.mjs': A_PLUGIN,
    })
    const nitro = await createNitro({
      rootDir: root,
      dev: false,
      preset: 'standard',
      modules: [mcp()],
    })

    const template = nitro.options.virtual['#mcp/mcp/handler']

    await expect(typeof template === 'function' ? template() : undefined).rejects.toThrow(
      /\/mcp has more than one plugins file \(plugins\.mjs, plugins\.ts\)/,
    )

    await nitro.close()
    await rm(root, { recursive: true, force: true })
  })
})
