packages:
  - apps/*
  - packages/*

shamefullyHoist: true
strictPeerDependencies: false

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  unrs-resolver: false
  vue-demi: false
  cbor-extract: false
  core-js-pure: false
  better-sqlite3: true
  isolated-vm: true
  sharp: true
  '@mongodb-js/zstd': true
  node-liblzma: true

overrides:
  '@nuxtjs/mcp-toolkit': workspace:*

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  # Nuxt
  - '@nuxt/*'
  - '@nuxtjs/*'
  - 'nuxt'
  - 'nuxt-*'
  - 'docus'
  # Vercel
  - '@vercel/*'
  - '@ai-sdk/*'
  - 'ai'
  - shaders@2.5.128
  - agents
  - '@iconify-json/simple-icons@1.2.86'
  - '@vue/language-core'
  - vue-tsc
  - better-sqlite3@12.10.1
