packages:
  - apps/*
  - packages/*

shamefullyHoist: true
strictPeerDependencies: false

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  unrs-resolver: false
  vue-demi: false
  cbor-extract: false
  core-js-pure: false
  better-sqlite3: true
  isolated-vm: true
  sharp: true
  '@mongodb-js/zstd': true
  node-liblzma: true

overrides:
  '@nuxtjs/mcp-toolkit': workspace:*
  unhead: ^3.2.3
  '@unhead/vue': ^3.2.3

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  # Nuxt
  - '@nuxt/*'
  - '@nuxtjs/*'
  - 'nuxt'
  - 'nuxt-*'
  - 'docus'
  # Vercel
  - '@vercel/*'
  - '@ai-sdk/*'
  - 'ai'
  - shaders@3.0.445
  - agents
  - '@iconify-json/simple-icons'
  - '@unhead/*'
  - 'unhead'
  - '@vue-macros/*'
  - 'undici'
  - '@vue/language-core'
  - vue-tsc
  - better-sqlite3@12.10.1
  - '@modelcontextprotocol/sdk@1.30.0'
  - '@modelcontextprotocol/client@2.0.0'
  - '@modelcontextprotocol/core@2.0.0'
  - '@modelcontextprotocol/server@2.0.0'
