import { DEFINITION_DIRS } from './discover.ts'
import type { DefinitionDir, DiscoveredDefinition } from './discover.ts'
import type { McpServerOptions } from './options.ts'

const BANNER = '// Generated by nitro-mcp-toolkit. Edit the files it lists instead.'

/**
 * Fills in what a definition left to its filename, and records where it was
 * found. Inlined rather than imported so the registry only ever pulls in the
 * definition files themselves.
 */
const FROM_FILE = `const fromFile = (definition, { name, title, ...source }) => ({
  ...definition,
  name: definition.name ?? name,
  title: definition.title ?? title,
  source,
})`

function entry(definition: DiscoveredDefinition, index: number): string {
  const { name, title, file, group } = definition
  const source = { name, title, file, ...(group ? { group } : {}) }

  return `  fromFile(_${index}, ${JSON.stringify(source)}),`
}

function list(dir: DefinitionDir, definitions: DiscoveredDefinition[]): string {
  const entries = definitions
    .map((definition, index) => (definition.dir === dir ? entry(definition, index) : undefined))
    .filter((line) => line !== undefined)

  return entries.length === 0
    ? `export const ${dir} = []`
    : `export const ${dir} = [\n${entries.join('\n')}\n]`
}

/**
 * The module the handler reads its definitions from: one import per discovered
 * file, and one array per kind.
 */
export function renderRegistry(definitions: DiscoveredDefinition[]): string {
  const blocks = [BANNER]

  if (definitions.length > 0) {
    blocks.push(
      definitions.map((d, index) => `import _${index} from ${JSON.stringify(d.path)}`).join('\n'),
      FROM_FILE,
    )
  }

  blocks.push(...DEFINITION_DIRS.map((dir) => list(dir, definitions)))

  return `${blocks.join('\n\n')}\n`
}

/** The route handler: the discovered registry, served on the module's route. */
export function renderHandler(registryId: string, server: McpServerOptions): string {
  const options = Object.entries(server)
    .filter(([, value]) => value !== undefined)
    .map(([key, value]) => `  ${key}: ${JSON.stringify(value)},`)

  return `${BANNER}
import { createMcpHandler } from 'nitro-mcp-toolkit'
import { prompts, resources, tools } from ${JSON.stringify(registryId)}

export default createMcpHandler({
${[...options, '  tools,', '  resources,', '  prompts,'].join('\n')}
})
`
}
