import { DEFINITION_DIRS } from './discover.ts'
import type { DefinitionDir, DiscoveredDefinition } from './discover.ts'
import type { McpServerOptions, ResolvedMcpOAuthOptions } from './options.ts'

const BANNER = '// Generated by nitro-mcp-toolkit. Edit the files it lists instead.'

/**
 * Fills in what a definition left to its filename, and records where it was
 * found. Inlined rather than imported so the registry only ever pulls in the
 * definition files themselves.
 */
const FROM_FILE = `const fromFile = (definition, { name, title, ...source }) => ({
  ...definition,
  name: definition.name ?? name,
  title: definition.title ?? title,
  source,
})`

function entry(definition: DiscoveredDefinition, index: number): string {
  const { name, title, file, group } = definition
  const source = { name, title, file, ...(group ? { group } : {}) }

  return `  fromFile(_${index}, ${JSON.stringify(source)}),`
}

function list(dir: DefinitionDir, definitions: DiscoveredDefinition[]): string {
  const entries = definitions
    .map((definition, index) => (definition.dir === dir ? entry(definition, index) : undefined))
    .filter((line) => line !== undefined)

  return entries.length === 0
    ? `export const ${dir} = []`
    : `export const ${dir} = [\n${entries.join('\n')}\n]`
}

/**
 * The module the handler reads its definitions from: one import per discovered
 * file, and one array per kind.
 */
export function renderRegistry(definitions: DiscoveredDefinition[]): string {
  const blocks = [BANNER]

  if (definitions.length > 0) {
    blocks.push(
      definitions.map((d, index) => `import _${index} from ${JSON.stringify(d.path)}`).join('\n'),
      FROM_FILE,
    )
  }

  blocks.push(...DEFINITION_DIRS.map((dir) => list(dir, definitions)))

  return `${blocks.join('\n\n')}\n`
}

function line(key: string, value: unknown): string {
  return `  ${key}: ${JSON.stringify(value)},`
}

/** The `createMcpOAuth` instance the handler and metadata routes share. */
export function renderOAuth(oauth: ResolvedMcpOAuthOptions): string {
  return `${BANNER}
import { createMcpOAuth } from 'nitro-mcp-toolkit'

export const oauth = createMcpOAuth({
${line('resource', oauth.resource)}
${line('authorizationServers', oauth.authorizationServers)}
${oauth.scopesSupported ? `${line('scopesSupported', oauth.scopesSupported)}\n` : ''}${line('jwt', oauth.jwt)}${
    oauth.authorizationServer ? `\n${line('authorizationServer', oauth.authorizationServer)}` : ''
  }
})
`
}

/** RFC 9728 document, mounted at the path RFC 9728 derives from `resource`. */
export function renderOAuthMetadata(oauthId: string): string {
  return `${BANNER}
import { oauth } from ${JSON.stringify(oauthId)}

export default oauth.metadataHandler
`
}

/** RFC 8414 document, proxied from the authorization server. */
export function renderAuthorizationServer(oauthId: string): string {
  return `${BANNER}
import { oauth } from ${JSON.stringify(oauthId)}

export default oauth.authorizationServerHandler
`
}

/** What the handler wires in beyond the registry, when the app asked for it. */
export interface HandlerWiring {
  /** The `createMcpOAuth` instance to take `auth` from. */
  oauthId?: string
  /** Absolute path of the plugins file, whose default export is installed. */
  pluginsPath?: string
}

/** The route handler: the discovered registry, served on the module's route. */
export function renderHandler(
  registryId: string,
  server: McpServerOptions,
  wiring: HandlerWiring = {},
): string {
  const { oauthId, pluginsPath } = wiring
  const options = Object.entries(server)
    .filter(([, value]) => value !== undefined)
    .map(([key, value]) => line(key, value))

  if (oauthId) options.push('  auth: oauth.auth,')

  const imports = [
    `import { createMcpHandler } from 'nitro-mcp-toolkit'`,
    ...(oauthId ? [`import { oauth } from ${JSON.stringify(oauthId)}`] : []),
    ...(pluginsPath ? [`import plugins from ${JSON.stringify(pluginsPath)}`] : []),
    `import { prompts, resources, tools } from ${JSON.stringify(registryId)}`,
  ]

  const setup = pluginsPath ? ', { extensionPlugins: plugins }' : ''

  return `${BANNER}
${imports.join('\n')}

export default createMcpHandler({
${[...options, '  tools,', '  resources,', '  prompts,'].join('\n')}
}${setup})
`
}

/** Named re-exports of every mounted handler. Virtual id: `nitro-mcp-toolkit/servers`. */
export function renderServers(
  instances: readonly { exportName: string; handlerId: string }[],
): string {
  const exports = instances.map(
    (instance) =>
      `export { default as ${instance.exportName} } from ${JSON.stringify(instance.handlerId)}`,
  )

  return `${BANNER}\n${exports.join('\n')}\n`
}

/**
 * App-specific names (`adminMcp`, …) the published stub cannot list. Merged
 * onto `nitro-mcp-toolkit/servers` once Nitro writes its types.
 */
export function renderServerTypes(instances: readonly { exportName: string }[]): string {
  const names = instances
    .map((instance) => `  export const ${instance.exportName}: McpHandler`)
    .join('\n')

  return `declare module 'nitro-mcp-toolkit/servers' {
  import type { McpHandler } from 'nitro-mcp-toolkit'
${names}
}
`
}
